apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: se03ex02
  labels:
    app: wpblog
    component: testing # No frontend? You shall not pass !!!!
spec:
  selector:
    matchLabels:
      app: wpblog
      component: testing # No frontend? You shall not pass !!!!
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
