apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: se03ex02
  labels:
    app: wpblog
    component: backend
spec:
  type: ClusterIP
  ports:
  - name: mysqlport
    port: 3306
    targetPort: 3306
  selector:
    component: backend